### ISSUE TITLE
consider rules to enhance pictures

### ISSUE THREAD

**Issue by rogerallen** [rogerallen/tweegeemee#15]
From a twitter conversation with @zedshaw ...

> This book might be helpful http://www.amazon.com/The-Simple-Secret-Better-Painting/dp/1581802560 …

I responded:

> interesting idea, but hard to implement. Good/bad are "easy" via the judgment of followers. Maybe they should read this?

And he replied

> No, it's not good bad. It's a set of simple easy to implement rules. Trust me. Get it. I know code, they are implementable. In fact, I believe most of it can be implemented using Cassowary http://constraints.cs.washington.edu/cassowary/

I'll have to give this book a look.  I'm not familiar with it or Cassowary.

**Comment by rogerallen** [comment]
Some quick thoughts:

I like that interesting & perhaps beautiful imagery arises with very few rules, currently.  The current rules are only:
- not too dark
- must have some color variation

By leveraging twitter follower's judgement + simple genetic algorithms to breed new images, this allows us to explore the maximum design space.  

I fear that adding constraints could keep us from exploring that large design space and overconstrain us from producing whole swaths of new imagery that could be interesting.  I wouldn't want that.

That said, If I could have a simple rule to avoid all the stupid checkerboards, that might be worth it!  :smile:   It also might be a reasonable "pivot" for tweegeemee to take as a new/different design tool.

**Comment by zedshaw** [comment]
The book's actual only rule is:

Never make any two things equal.

That's it.  If you have "not too dark" then you're already doing something like it.  It then uses that to show how many other composition "rules" are just some form of that.  For example, using a color scheme that is a lot of a color, some of a color, and very little of another, is simply a way to make color use not all equal.  Or, rule of thirds is just a way to frame and place the elements so they are not equally near each other or near the edge of the frame.

And, "constraint" in this case is just the math term.  You are already constrained by the frame, so a composition system just helps you use the frame to the best ability.  Throw in color composition and you'll have a higher probability of making something pleasing and interesting.

My thinking on Cassowary is not so much to use it, but the idea that you'd generate a random constraint set, adjust it so no constraint is an equality, then you'd put form placement through it so that the choice of where to place a line is adjusted based on where other lines/shapes are to be not equal all the time.  Then you could have a similar one for color that makes sure color and value choices are not equal.

Anyway, that was just my thought.

**Comment by rogerallen** [comment]
Thanks for explaining.  Will consider this some more...
